- hosts: ec2
  tasks:
          - package: "name=httpd    state=present"
          - copy:    "src=/root/ec2_ansible/index.html   dest=/var/www/html"
          - service: "name=httpd   state=started"
